# CloudFormation Template
AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Template for AWS Resume Web"

Parameters:
  BucketName:
    Type: String
    Description: "Name of the S3 bucket to create"

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: WebsiteBucket
    Properties:
      Bucket:
        Ref: WebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: WebsiteBucket
                  - "/*"

Outputs:
  WebsiteURL:
    Description: "Website URL"
    Value:
      Fn::GetAtt:
        - WebsiteBucket
        - WebsiteURL
  BucketName:
    Description: "S3 Bucket Name"
    Value:
      Ref: WebsiteBucket
