AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda function for GitHub to S3 sync"

Parameters:
  BucketName:
    Type: String
    Description: "S3 bucket name for sync target"
    Default: "s3.huyng2603.io"

  RepoUrl:
    Type: String
    Description: "GitHub repository URL"
    Default: "https://github.com/HuyNguyen260398/aws_resume_web_src.git"

  Branch:
    Type: String
    Description: "Git branch to sync"
    Default: "main"

  GitHubToken:
    Type: String
    Description: "GitHub personal access token (optional, for private repos)"
    Default: ""
    NoEcho: true

Resources:
  # IAM Role for Lambda
  GitHubSyncLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3SyncPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:HeadObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${BucketName}"
                  - !Sub "arn:aws:s3:::${BucketName}/*"

  # Lambda Function
  GitHubSyncFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: github-s3-sync
      Runtime: python3.9
      Handler: lambda_github_s3_sync.lambda_handler
      Role: !GetAtt GitHubSyncLambdaRole.Arn
      Code:
        ZipFile: |
          # Placeholder - replace with actual deployment package
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Deploy actual code'}
      Timeout: 900 # 15 minutes max
      MemorySize: 1024
      Environment:
        Variables:
          GITHUB_TOKEN: !Ref GitHubToken
      Description: "Sync GitHub repository to S3 bucket"

  # EventBridge Rule for scheduled sync (optional)
  ScheduledSyncRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Trigger GitHub sync every hour"
      ScheduleExpression: "rate(1 hour)"
      State: DISABLED # Enable manually if needed
      Targets:
        - Arn: !GetAtt GitHubSyncFunction.Arn
          Id: "GitHubSyncTarget"
          Input: !Sub |
            {
              "repo_url": "${RepoUrl}",
              "bucket_name": "${BucketName}",
              "branch": "${Branch}"
            }

  # Permission for EventBridge to invoke Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GitHubSyncFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledSyncRule.Arn

Outputs:
  LambdaFunctionArn:
    Description: "Lambda function ARN"
    Value: !GetAtt GitHubSyncFunction.Arn

  LambdaFunctionName:
    Description: "Lambda function name"
    Value: !Ref GitHubSyncFunction
