AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for AWS Resume Web

Metadata:
  RecommendedStackName: s3-static-web
  DeploymentCommand: |
    aws cloudformation deploy \
      --template-file cloudformation_templates/s3_static_web_deployment.yaml \
      --stack-name s3-static-web \
      --capabilities CAPABILITY_IAM \
      --parameter-overrides BucketName=your-bucket-name

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket to create
    Default: s3.nghuy.link

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref WebsiteBucket
                - /*

Outputs:
  WebsiteURL:
    Description: Website URL
    Value: !GetAtt WebsiteBucket.WebsiteURL
  BucketName:
    Description: S3 Bucket Name
    Value: !Ref WebsiteBucket